import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

const Home: NextPage = () => {

  const user = useUser();

  const { data } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>🐦MojiTweet</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && <SignOutButton />}
        </div>

        <div>
          {
            data?.map((post) => (
              <div key={post.id}>
                <p>{post.content}</p>
              </div>
            ))
          }
        </div>

        <SignIn path="/sign-in" routing="path" />
      </main>
    </>
  );
};

export default Home;
